#############################################################################
# Makefile for building: qtemu
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri Oct 10 06:23:03 2014
# Project:  qtemu.pro
# Template: app
# Command: /home/kenn/work/ti/sdk/linux-devkit/sysroots/i686-arago-linux/usr/bin/qmake -o Makefile qtemu.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = /home/kenn/work/ti/sdk/linux-devkit/sysroots/i686-arago-linux/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: qtemu.pro  /usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/linux-g++/qmake.conf /usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/unix.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/linux.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/default_pre.prf \
		GuestTools/modules/clipboard/host.pri \
		GuestTools/modules/host.pri \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/release.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/debug_and_release.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/moc.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/dbusinterfaces.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/dbusadaptors.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/resources.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/uic.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/lex.prf \
		/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qtemu.pro
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/unix.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/linux.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/g++-base.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/common/g++-unix.conf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt_config.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/default_pre.prf:
GuestTools/modules/clipboard/host.pri:
GuestTools/modules/host.pri:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/release.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/debug_and_release.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/default_post.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/warn_on.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/qt.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/moc.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/dbusinterfaces.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/dbusadaptors.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/resources.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/uic.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/yacc.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/lex.prf:
/usr/local/qt-everywhere-opensource-src-4.8.5/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qtemu.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

/home/kenn/work/ti/sdk/linux-devkit/sysroots/i686-arago-linux/usr/bin/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
